server:
  port: 8102

spring:
  application:
    name: CATALOG-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/