apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  labels:
    app: config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
        - name: config-server-app
          image: samueletedocker/config-service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9296

---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  ports:
    - targetPort: 9296
      port: 80
  selector:
    app: config-server-app