spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/godwin/protocol/openid-connect/certs
  application:
    name: ACCOUNT-SERVICE
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8001
ribbon:
  eureka:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
