apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-app
  labels:
    app: account-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : account-service-app
  template:
    metadata:
      labels:
        app: account-service-app
    spec:
      containers:
      - name: account-service-app
        image: samueletedocker/account-service:v1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8001

---

kind: Service
apiVersion: v1
metadata:
  name:  account-service-svc
spec:
  selector:
    app:  account-service-app
  ports:
  - port:  80
    targetPort:  8001