---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /prometheus
      prometheus.io/port: "9411"
      fabric8.io/app-menu: management
      fabric8.io/git-commit: 1f8f74e5427eae1ef9b9d743b133f0c971432591
      fabric8.io/git-branch: release-v0.1.12
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/kubeflix.git/zipkin
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/kubeflix.git/zipkin
      fabric8.io/scm-tag: 0.1.12
      fabric8.io/scm-url: http://github.com/fabric8io/kubeflix/zipkin/
    labels:
      provider: fabric8
      project: zipkin
      version: 0.1.12
      group: io.fabric8.zipkin
      expose: "true"
    name: zipkin
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 9411
    selector:
      project: zipkin
      provider: fabric8
      group: io.fabric8.zipkin
    type: LoadBalancer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 1f8f74e5427eae1ef9b9d743b133f0c971432591
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.12
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/kubeflix.git/zipkin
      fabric8.io/scm-url: http://github.com/fabric8io/kubeflix/zipkin/
      fabric8.io/git-branch: release-v0.1.12
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/kubeflix.git/zipkin
      fabric8.io/scm-tag: 0.1.12
    labels:
      provider: fabric8
      project: zipkin
      version: 0.1.12
      group: io.fabric8.zipkin
    name: zipkin
  spec:
    replicas: 1
    selector:
      matchLabels:
        provider: fabric8
        project: zipkin
        group: io.fabric8.zipkin
        version: 0.1.12
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 1f8f74e5427eae1ef9b9d743b133f0c971432591
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.12
          fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/kubeflix.git/zipkin
          fabric8.io/scm-url: http://github.com/fabric8io/kubeflix/zipkin/
          fabric8.io/git-branch: release-v0.1.12
          fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/kubeflix.git/zipkin
          fabric8.io/scm-tag: 0.1.12
        labels:
          provider: fabric8
          project: zipkin
          version: 0.1.12
          group: io.fabric8.zipkin
      spec:
        containers:
        - env:
          - name: STORAGE_PORT_9042_TCP_ADDR
            value: zipkin-cassandra:9411
          - name: STORAGE_PORT_3306_TCP_ADDR
            value: zipkin-mysql:3306
          - name: STORAGE_TYPE
            value: mysql
          - name: TRANSPORT_TYPE
            value: http
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: openzipkin/zipkin:1.25.0
          name: zipkin
          readinessProbe:
            httpGet:
              path: /api/v1/services
              port: 9411
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
